### ISSUE TITLE
Encrypted backup support

### ISSUE THREAD

**Issue by rtammekivi** [Maxmad68/ibake#1]
Do you have plans to add support for encrypted backups?

**Comment by Maxmad68** [comment]
To be honest, I never thought about encrypted backups.
This is not a bad idea, I will consider it for a future version.

--
Maxmad68

**Comment by rtammekivi** [comment]
At the moment I need to encrypt the backup to properly restore Wi-Fi configuration. It seems like this is not backed up on unencrypted backups.

I've seen iMazing be able to decrypt these backups, I wonder how difficult it might be.

**Comment by Maxmad68** [comment]
Sorry for the late answer.
I'm currently passing some exams, I will take this into account as soon as possible.
